name: scilab-environment
channels:
      - conda-forge
dependencies:
      - python
      - numpy
      - pip
      - pip:
        - nbgitpuller
        - sphinx-gallery
        - pandas
        - matplotlib
        - metakernel
        - scilab_kernel

