#!/bin/bash

set -ex

# Download and local install Scilab 
VERSION=6.1.0
curl https://www.scilab.org/download/$VERSION/scilab-$VERSION.bin.linux-x86_64.tar.gz |tar xzf -
export PATH=$PATH:$(pwd)/scilab-$VERSION/bin

