#!/bin/bash

set -ex

# Download and local install Scilab 
VERSION=6.1.0
if [ ! -d scilab-$VERSION ]; then
    curl https://www.scilab.org/download/$VERSION/scilab-$VERSION.bin.linux-x86_64.tar.gz |tar xzf -
fi
PATH=$PATH:$(pwd)/scilab-$VERSION/bin
export PATH

